# latest_posts: Latest Posts
# read_more: Read More
# powered_by: Powered by
# prev: Prev
# next: Next
# archive: Archive
# about_this_post: About this Post
# this_post_is_written_by: This post is written by
# licensed_under: licensed under
# home: Home
latest_posts: 最新文章
read_more: 继续阅读
powered_by: 驱动由
prev: 上一页
next: 下一页
archive: 存档
about_this_post: 关于本文
this_post_is_written_by: 本文作者
licensed_under: 许可由
home: 主页
